# Generated by Django 4.0.3 on 2022-03-23 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('questions', '0004_remove_question_downvotes_remove_question_upvotes_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('teacher', 'question')},
        ),
    ]
