# Generated by Django 4.0.3 on 2022-08-13 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_paper_questionpaper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='setter',
            new_name='teacher',
        ),
    ]
