# Generated by Django 4.0.3 on 2022-08-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_rename_setter_paper_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='name',
            field=models.CharField(default='End Semester Paper', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='medium',
            field=models.CharField(default='English', max_length=50),
            preserve_default=False,
        ),
    ]
