# Generated by Django 4.0.3 on 2022-08-15 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_paper_created_at_paper_question_delete_questionpaper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='question',
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.paper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
            options={
                'unique_together': {('paper', 'question')},
            },
        ),
    ]
