# Generated by Django 4.0.3 on 2022-08-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='reason',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
